CREATE TABLE WALLET (
  ID SERIAL PRIMARY KEY,
  USERNAME VARCHAR(64) UNIQUE,
  BALANCE NUMERIC NOT NULL DEFAULT 0
);

CREATE TABLE TRANSACTION (
    ID SERIAL PRIMARY KEY,
    SENDER_WALLET_ID INTEGER,
    RECEIVER_WALLET_ID INTEGER,
    AMOUNT NUMERIC,
    "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    TRANSACTION_REASON VARCHAR(128),
    CONSTRAINT FK_SENDER_WALLET FOREIGN KEY (SENDER_WALLET_ID)
    REFERENCES WALLET (ID),
    CONSTRAINT FK_RECEIVER_WALLET FOREIGN KEY (RECEIVER_WALLET_ID)
    REFERENCES WALLET (ID)
);